CREATE TABLE `user`(
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(20) NOT NULL DEFAULT '',
	`age` INT UNSIGNED NOT NULL DEFAULT 0,
	PRIMARY KEY(`id`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

INSERT INTO `user` (`name`, `age`) VALUES
('张三',18),
('李四',16),
('王五',17),
('赵六',21);
